baseURL: "/"
languageCode: "ko-kr"
title: "Youngbin Han's blog"
# theme: github.com/gethugothemes/bookworm-light
permalinks: 
  blog: /:filename
paginate: 10
summaryLength: 50
params:
  copyrights: Copyright © 2022 - Present Youngbin Han
  giscus:
    repo: sukso96100/blog.youngbin.xyz
    repoId: MDEwOlJlcG9zaXRvcnkxODYyMDAzMDc
    category: Blog Comments
    categoryId: DIC_kwDOCxkw884CUi58
  mainSections: ["blog"]
  search: true
  author: Youngbin Han
  social:
    - icon: lab la-facebook-f
      url: 'https://www.facebook.com/hanyoungbin'
    - icon: lab la-twitter
      url: 'https://www.twitter.com/sukso96100'
    - icon: lab la-instagram
      url: 'https://www.instagram.com/hanyoungbin'
    - icon: lab la-linkedin-in
      url: 'https://www.linkedin.com/in/youngbin-han/'
    - icon: lab la-github
      url: 'https://github.com/sukso96100'
  adsense:
    client: 'ca-pub-7051197638651710'
    adslot: '4463380264'
menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
    - identifier: rss 
      name: Subscribe (RSS)
      url: /index.xml
      weight: 20
    - identifier: website
      name: youngbin.xyz
      url: https://youngbin.xyz
      weight: 30

outputs: 
  home: ["HTML", "RSS", "JSON"]
markup:
  goldmark:
    renderer:
      unsafe: true