backend:
  name: test-repo
  # name: git-gateway
  # branch: master
publish_mode: editorial_workflow

locale: 'ko'
site_url: https://blog.youngbin.xyz
display_url: https://blog.youngbin.xyz
media_folder: static/img
public_folder: /img
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Cover Image", name: "image", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
